# Generated by Django 3.2.22 on 2023-10-31 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('accno', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rc', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripfrom', models.CharField(max_length=30)),
                ('tripto', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('timefrom', models.CharField(max_length=10)),
                ('timeto', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.login')),
            ],
        ),
        migrations.CreateModel(
            name='TravelBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rc', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('regno', models.CharField(max_length=20)),
                ('TRAVELAGENCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.travelagency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.login')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('TRAVELBUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.travelbus')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.user')),
            ],
        ),
        migrations.CreateModel(
            name='TravelAllocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route')),
                ('TRAVELBUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.travelbus')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.login')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBusSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('SCHEDULEBUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.schedulebus')),
            ],
        ),
        migrations.AddField(
            model_name='schedulebus',
            name='TRAVELALLOCATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.travelallocate'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('rating', models.FloatField(max_length=5)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('license', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.login')),
                ('OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default=0, max_length=10)),
                ('setontime', models.CharField(max_length=10)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('complaindate', models.CharField(max_length=15)),
                ('reply', models.CharField(max_length=300)),
                ('replydate', models.CharField(max_length=15)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('TRAFFICPOLICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.trafficpolice')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bustime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route')),
                ('STOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Busroute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.owner'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatlist', models.CharField(max_length=200)),
                ('SCHEDULEBUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.schedulebus')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('TRAFFICPOLICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.trafficpolice')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.driver')),
            ],
        ),
    ]
